doks:
    baseurl:
    color_theme: blue
    micro_nav:
    - title: About
      url: '/'


    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Documentation
              item_url: /
            - item_name: Icons
              item_url: https://icons8.com
              external_url: true
            - item_name: Blog
              item_url: https://blog.icons8.com
              external_url: true
            - item_name: Forum
              item_url: https://community.icons8.com
              external_url: true


    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/

# theme: jekyll-theme-cayman
